2014/12/16 00:49:37 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in D:\xampp\htdocs\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 D:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 D:\xampp\htdocs\yii\framework\web\auth\CDbAuthManager.php(589): CModule->getComponent('db')
#4 D:\xampp\htdocs\yii\framework\web\auth\CDbAuthManager.php(59): CDbAuthManager->getDbConnection()
#5 D:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbAuthManager->init()
#6 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(185): CModule->getComponent('authManager')
#7 D:\xampp\htdocs\yii\framework\web\auth\CWebUser.php(815): CWebApplication->getAuthManager()
#8 D:\xampp\htdocs\erp_started\protected\views\site\index.php(18): CWebUser->checkAccess('admin')
#9 D:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('D:\xampp\htdocs...')
#10 D:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('D:\xampp\htdocs...', NULL, true)
#11 D:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('D:\xampp\htdocs...', NULL, true)
#12 D:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#13 D:\xampp\htdocs\erp_started\protected\controllers\SiteController.php(32): CController->render('index')
#14 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#19 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#20 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Erp_started/index.php
---
2014/12/16 00:49:55 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in D:\xampp\htdocs\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 D:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 D:\xampp\htdocs\yii\framework\web\auth\CDbAuthManager.php(589): CModule->getComponent('db')
#4 D:\xampp\htdocs\yii\framework\web\auth\CDbAuthManager.php(59): CDbAuthManager->getDbConnection()
#5 D:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbAuthManager->init()
#6 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(185): CModule->getComponent('authManager')
#7 D:\xampp\htdocs\yii\framework\web\auth\CWebUser.php(815): CWebApplication->getAuthManager()
#8 D:\xampp\htdocs\erp_started\protected\views\site\index.php(18): CWebUser->checkAccess('admin')
#9 D:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('D:\xampp\htdocs...')
#10 D:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('D:\xampp\htdocs...', NULL, true)
#11 D:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('D:\xampp\htdocs...', NULL, true)
#12 D:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#13 D:\xampp\htdocs\erp_started\protected\controllers\SiteController.php(32): CController->render('index')
#14 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#19 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#20 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Erp_started/index.php
---
2014/12/16 00:58:35 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in D:\xampp\htdocs\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 D:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 D:\xampp\htdocs\yii\framework\cli\commands\MigrateCommand.php(442): CModule->getComponent('db')
#4 D:\xampp\htdocs\yii\framework\cli\commands\MigrateCommand.php(451): MigrateCommand->getDbConnection()
#5 D:\xampp\htdocs\yii\framework\cli\commands\MigrateCommand.php(482): MigrateCommand->getMigrationHistory(-1)
#6 D:\xampp\htdocs\yii\framework\cli\commands\MigrateCommand.php(84): MigrateCommand->getNewMigrations()
#7 [internal function]: MigrateCommand->actionUp(Array)
#8 D:\xampp\htdocs\yii\framework\console\CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#9 D:\xampp\htdocs\yii\framework\console\CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#10 D:\xampp\htdocs\yii\framework\console\CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#11 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CConsoleApplication->processRequest()
#12 D:\xampp\htdocs\yii\framework\yiic.php(33): CApplication->run()
#13 D:\xampp\htdocs\erp_started\protected\yiic.php(7): require_once('D:\xampp\htdocs...')
#14 D:\xampp\htdocs\erp_started\protected\yiic(4): require_once('D:\xampp\htdocs...')
#15 {main}
---
2014/12/16 01:00:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: YES)' in D:\xampp\htdocs\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 D:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 D:\xampp\htdocs\yii\framework\web\auth\CDbAuthManager.php(589): CModule->getComponent('db')
#4 D:\xampp\htdocs\yii\framework\web\auth\CDbAuthManager.php(59): CDbAuthManager->getDbConnection()
#5 D:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbAuthManager->init()
#6 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(185): CModule->getComponent('authManager')
#7 D:\xampp\htdocs\yii\framework\web\auth\CWebUser.php(815): CWebApplication->getAuthManager()
#8 D:\xampp\htdocs\erp_started\protected\views\site\index.php(18): CWebUser->checkAccess('admin')
#9 D:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('D:\xampp\htdocs...')
#10 D:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('D:\xampp\htdocs...', NULL, true)
#11 D:\xampp\htdocs\yii\framework\web\CController.php(869): CBaseController->renderFile('D:\xampp\htdocs...', NULL, true)
#12 D:\xampp\htdocs\yii\framework\web\CController.php(782): CController->renderPartial('index', NULL, true)
#13 D:\xampp\htdocs\erp_started\protected\controllers\SiteController.php(32): CController->render('index')
#14 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#15 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#16 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#17 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#18 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#19 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#20 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#21 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#22 {main}
REQUEST_URI=/Erp_started/index.php
---
2014/12/16 01:26:30 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'erp_started2'' in D:\xampp\htdocs\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 D:\xampp\htdocs\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 D:\xampp\htdocs\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 D:\xampp\htdocs\yii\framework\cli\commands\MigrateCommand.php(442): CModule->getComponent('db')
#4 D:\xampp\htdocs\yii\framework\cli\commands\MigrateCommand.php(451): MigrateCommand->getDbConnection()
#5 D:\xampp\htdocs\yii\framework\cli\commands\MigrateCommand.php(482): MigrateCommand->getMigrationHistory(-1)
#6 D:\xampp\htdocs\yii\framework\cli\commands\MigrateCommand.php(84): MigrateCommand->getNewMigrations()
#7 [internal function]: MigrateCommand->actionUp(Array)
#8 D:\xampp\htdocs\yii\framework\console\CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#9 D:\xampp\htdocs\yii\framework\console\CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#10 D:\xampp\htdocs\yii\framework\console\CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#11 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CConsoleApplication->processRequest()
#12 D:\xampp\htdocs\yii\framework\yiic.php(33): CApplication->run()
#13 D:\xampp\htdocs\erp_started\protected\yiic.php(7): require_once('D:\xampp\htdocs...')
#14 D:\xampp\htdocs\erp_started\protected\yiic(4): require_once('D:\xampp\htdocs...')
#15 {main}
---
2014/12/16 01:26:43 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'erp_plastiplas.tbl_migration' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_migration`.
2014/12/16 06:11:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "puntoVenta/admin"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('puntoVenta/admi...')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Erp_started/index.php?r=puntoVenta/admin
HTTP_REFERER=http://localhost/Erp_started/index.php?r=cliente/admin
---
2014/12/16 06:21:40 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "puntoVenta/admin"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('puntoVenta/admi...')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Erp_started/index.php?r=puntoVenta/admin
HTTP_REFERER=http://localhost/Erp_started/index.php?r=cliente/admin
---
2014/12/16 06:21:44 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested detalle venta does not exist.' in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:465
Stack trace:
#0 D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php(439): DetalleVentaController->loadVenta(NULL)
#1 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterVentaContext(Object(CFilterChain))
#2 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#3 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#8 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#10 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('detalleVenta/ad...')
#11 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/Erp_started/index.php?r=detalleVenta/admin
HTTP_REFERER=http://localhost/Erp_started/index.php?r=puntoVenta/admin
---
2014/12/16 06:22:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested detalle venta does not exist.' in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:465
Stack trace:
#0 D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php(439): DetalleVentaController->loadVenta(NULL)
#1 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterVentaContext(Object(CFilterChain))
#2 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#3 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#8 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#10 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('detalleVenta/ad...')
#11 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/Erp_started/index.php?r=detalleVenta/admin
HTTP_REFERER=http://localhost/Erp_started/index.php?r=puntoVenta/admin
---
2014/12/16 06:26:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested detalle venta does not exist.' in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:465
Stack trace:
#0 D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php(439): DetalleVentaController->loadVenta(NULL)
#1 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterVentaContext(Object(CFilterChain))
#2 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#3 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#8 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#10 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('detalleVenta/ad...')
#11 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/Erp_started/index.php?r=detalleVenta/admin
HTTP_REFERER=http://localhost/Erp_started/index.php?r=puntoVenta/admin
---
2014/12/16 20:08:27 [error] [exception.CException] exception 'CException' with message 'La propiedad "Venta"."cliente" no se encuentra definida.' in D:\xampp\htdocs\yii\framework\base\CComponent.php:173
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(161): CComponent->__set('cliente', 0)
#1 D:\xampp\htdocs\erp_started\protected\controllers\VentaController.php(286): CActiveRecord->__set('cliente', 0)
#2 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): VentaController->actionCreateVenta()
#3 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#10 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('createVenta')
#12 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Venta/createVen...')
#13 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/Erp_started/index.php?r=Venta/createVenta
HTTP_REFERER=http://localhost/Erp_started/index.php?r=site/login
---
2014/12/16 20:08:41 [error] [exception.CException] exception 'CException' with message 'La propiedad "Venta"."formaPago" no se encuentra definida.' in D:\xampp\htdocs\yii\framework\base\CComponent.php:173
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(161): CComponent->__set('formaPago', 2)
#1 D:\xampp\htdocs\erp_started\protected\controllers\VentaController.php(288): CActiveRecord->__set('formaPago', 2)
#2 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): VentaController->actionCreateVenta()
#3 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#5 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#7 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#8 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#9 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#10 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('createVenta')
#12 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Venta/createVen...')
#13 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#14 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#15 {main}
REQUEST_URI=/Erp_started/index.php?r=Venta/createVenta
---
2014/12/16 20:09:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested detalle venta does not exist.' in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:465
Stack trace:
#0 D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php(439): DetalleVentaController->loadVenta('')
#1 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterVentaContext(Object(CFilterChain))
#2 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#3 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#8 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#10 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('DetalleVenta/cr...')
#11 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/Erp_started/index.php?r=DetalleVenta/create&pid=
---
2014/12/17 07:11:24 [error] [php] Missing argument 1 for CActiveRecord::setPrimaryKey(), called in D:\xampp\htdocs\erp_started\protected\controllers\VentaController.php on line 283 and defined (D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:1296)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): VentaController->runAction()
#2 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#3 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#4 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): VentaController->filterAccessControl()
#5 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#7 D:\xampp\htdocs\yii\framework\web\CController.php(265): VentaController->runActionWithFilters()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): VentaController->run()
#9 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#10 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#11 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/Erp_started/index.php?r=Venta/createVenta
in D:\xampp\htdocs\erp_started\protected\controllers\VentaController.php (283)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/17 23:29:26 [warning] [application] Error al establecer unsafe al atributo "ventaUnd" de "Producto".
in D:\xampp\htdocs\erp_started\protected\controllers\ProductoController.php (72)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/18 03:09:52 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'erp_plastiplas.tbl_migration' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_migration`.
2014/12/18 03:30:04 [error] [system.db.CDbCommand] CDbCommand::execute() failed: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`erp_plastiplas`.`tbl_venta`, CONSTRAINT `fk_cliente_venta` FOREIGN KEY (`cliente_id`) REFERENCES `tbl_cliente` (`id`) ON DELETE CASCADE). The SQL statement executed was: INSERT INTO `tbl_venta` (`fecha_venta`, `cliente_id`, `vendedor_id`, `forma_pago_id`, `estado`, `estado_comprobante`, `estado_pago`, `create_user_id`, `update_user_id`, `create_time`, `update_time`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, NOW(), NOW()).
in D:\xampp\htdocs\erp_started\protected\controllers\VentaController.php (293)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/18 03:30:04 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`erp_plastiplas`.`tbl_venta`, CONSTRAINT `fk_cliente_venta` FOREIGN KEY (`cliente_id`) REFERENCES `tbl_cliente` (`id`) ON DELETE CASCADE). The SQL statement executed was: INSERT INTO `tbl_venta` (`fecha_venta`, `cliente_id`, `vendedor_id`, `forma_pago_id`, `estado`, `estado_comprobante`, `estado_pago`, `create_user_id`, `update_user_id`, `create_time`, `update_time`) VALUES (:yp0, :yp1, :yp2, :yp3, :yp4, :yp5, :yp6, :yp7, :yp8, NOW(), NOW())' in D:\xampp\htdocs\yii\framework\db\CDbCommand.php:358
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1077): CDbCommand->execute()
#1 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(806): CActiveRecord->insert(NULL)
#2 D:\xampp\htdocs\erp_started\protected\controllers\VentaController.php(293): CActiveRecord->save()
#3 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): VentaController->actionCreateVenta()
#4 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#5 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#6 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#7 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#8 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#9 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#10 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#11 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('createVenta')
#13 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Venta/createVen...')
#14 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/Erp_started/index.php?r=Venta/createVenta
HTTP_REFERER=http://localhost/Erp_started/index.php?r=offer/admin
---
2014/12/18 03:36:41 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'erp_plastiplas.tbl_migration' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_migration`.
2014/12/18 04:08:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested detalle venta does not exist.' in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:465
Stack trace:
#0 D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php(439): DetalleVentaController->loadVenta(NULL)
#1 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterVentaContext(Object(CFilterChain))
#2 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#3 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#8 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#10 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('DetalleVenta/ad...')
#11 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/Erp_started/index.php?r=DetalleVenta/admin
---
2014/12/18 06:37:56 [error] [system.db.CDbCommand] CDbCommand::fetch() falló: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'and lote='' LIMIT 1' at line 1. La sentencia SQL ejecutada fue: SELECT fecha_vencimiento FROM `tbl_producto_almacen` `t` WHERE producto_id= and lote='' LIMIT 1.
in D:\xampp\htdocs\erp_started\protected\models\ProductoAlmacen.php (136)
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (74)
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (443)
2014/12/18 06:37:56 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand falló al ejecutar la sentencia SQL: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'and lote='' LIMIT 1' at line 1. The SQL statement executed was: SELECT fecha_vencimiento FROM `tbl_producto_almacen` `t` WHERE producto_id= and lote='' LIMIT 1' in D:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\CDbCommand.php(415): CDbCommand->queryInternal('fetch', Array, Array)
#1 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1351): CDbCommand->queryRow()
#2 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1456): CActiveRecord->query(Object(CDbCriteria))
#3 D:\xampp\htdocs\erp_started\protected\models\ProductoAlmacen.php(136): CActiveRecord->find(Object(CDbCriteria))
#4 D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php(74): ProductoAlmacen->getFecha_vencimiento('', NULL)
#5 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): DetalleVentaController->actionCreate()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php(443): CFilterChain->run()
#9 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterVentaContext(Object(CFilterChain))
#10 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#11 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#16 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#18 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('detalleVenta/cr...')
#19 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#20 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/Erp_started/index.php?r=detalleVenta/create&pid=4883
HTTP_REFERER=http://localhost/Erp_started/index.php?r=DetalleVenta/create&pid=4883
---
2014/12/18 06:39:14 [error] [system.db.CDbCommand] CDbCommand::fetch() falló: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'and lote='' LIMIT 1' at line 1. La sentencia SQL ejecutada fue: SELECT fecha_vencimiento FROM `tbl_producto_almacen` `t` WHERE producto_id= and lote='' LIMIT 1.
in D:\xampp\htdocs\erp_started\protected\models\ProductoAlmacen.php (136)
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (74)
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (443)
2014/12/18 06:39:14 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand falló al ejecutar la sentencia SQL: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'and lote='' LIMIT 1' at line 1. The SQL statement executed was: SELECT fecha_vencimiento FROM `tbl_producto_almacen` `t` WHERE producto_id= and lote='' LIMIT 1' in D:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\CDbCommand.php(415): CDbCommand->queryInternal('fetch', Array, Array)
#1 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1351): CDbCommand->queryRow()
#2 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1456): CActiveRecord->query(Object(CDbCriteria))
#3 D:\xampp\htdocs\erp_started\protected\models\ProductoAlmacen.php(136): CActiveRecord->find(Object(CDbCriteria))
#4 D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php(74): ProductoAlmacen->getFecha_vencimiento('', NULL)
#5 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): DetalleVentaController->actionCreate()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php(443): CFilterChain->run()
#9 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterVentaContext(Object(CFilterChain))
#10 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#11 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#16 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#18 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('detalleVenta/cr...')
#19 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#20 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/Erp_started/index.php?r=detalleVenta/create&pid=4883
HTTP_REFERER=http://localhost/Erp_started/index.php?r=DetalleVenta/create&pid=4883
---
2014/12/18 06:39:18 [error] [system.db.CDbCommand] CDbCommand::fetch() falló: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'and lote='' LIMIT 1' at line 1. La sentencia SQL ejecutada fue: SELECT fecha_vencimiento FROM `tbl_producto_almacen` `t` WHERE producto_id= and lote='' LIMIT 1.
in D:\xampp\htdocs\erp_started\protected\models\ProductoAlmacen.php (136)
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (74)
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (443)
2014/12/18 06:39:18 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand falló al ejecutar la sentencia SQL: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'and lote='' LIMIT 1' at line 1. The SQL statement executed was: SELECT fecha_vencimiento FROM `tbl_producto_almacen` `t` WHERE producto_id= and lote='' LIMIT 1' in D:\xampp\htdocs\yii\framework\db\CDbCommand.php:543
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\CDbCommand.php(415): CDbCommand->queryInternal('fetch', Array, Array)
#1 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1351): CDbCommand->queryRow()
#2 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1456): CActiveRecord->query(Object(CDbCriteria))
#3 D:\xampp\htdocs\erp_started\protected\models\ProductoAlmacen.php(136): CActiveRecord->find(Object(CDbCriteria))
#4 D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php(74): ProductoAlmacen->getFecha_vencimiento('', NULL)
#5 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): DetalleVentaController->actionCreate()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#8 D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php(443): CFilterChain->run()
#9 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterVentaContext(Object(CFilterChain))
#10 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#11 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#16 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#18 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('detalleVenta/cr...')
#19 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#20 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/Erp_started/index.php?r=detalleVenta/create&pid=4883
HTTP_REFERER=http://localhost/Erp_started/index.php?r=DetalleVenta/create&pid=4883
---
2014/12/19 04:47:32 [error] [system.db.CDbCommand] CDbCommand::fetchAll() falló: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'erp_started2.tbl_user' doesn't exist. La sentencia SQL ejecutada fue: SHOW FULL COLUMNS FROM `tbl_user`.
in D:\xampp\htdocs\erp_started\protected\components\UserIdentity.php (21)
in D:\xampp\htdocs\erp_started\protected\models\LoginForm.php (52)
in D:\xampp\htdocs\erp_started\protected\controllers\SiteController.php (94)
2014/12/19 04:47:32 [error] [exception.CDbException] exception 'CDbException' with message 'La tabla "tbl_user" definida en la clase active record "User" no se ha podido encontrar en la base de datos.' in D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2362
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(658): CActiveRecord->getMetaData()
#2 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1350): CActiveRecord->getTableSchema()
#3 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1456): CActiveRecord->query(Object(CDbCriteria))
#4 D:\xampp\htdocs\erp_started\protected\components\UserIdentity.php(21): CActiveRecord->find('LOWER(username)...', Array)
#5 D:\xampp\htdocs\erp_started\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#6 D:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#7 D:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#8 D:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#9 D:\xampp\htdocs\erp_started\protected\controllers\SiteController.php(94): CModel->validate()
#10 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#11 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#15 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#16 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/erp_started/index.php?r=site/login
HTTP_REFERER=http://localhost/erp_started/index.php?r=site/login
---
2014/12/19 04:47:52 [error] [system.db.CDbCommand] CDbCommand::fetchAll() falló: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'erp_started2.tbl_user' doesn't exist. La sentencia SQL ejecutada fue: SHOW FULL COLUMNS FROM `tbl_user`.
in D:\xampp\htdocs\erp_started\protected\components\UserIdentity.php (21)
in D:\xampp\htdocs\erp_started\protected\models\LoginForm.php (52)
in D:\xampp\htdocs\erp_started\protected\controllers\SiteController.php (94)
2014/12/19 04:47:52 [error] [exception.CDbException] exception 'CDbException' with message 'La tabla "tbl_user" definida en la clase active record "User" no se ha podido encontrar en la base de datos.' in D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2362
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(658): CActiveRecord->getMetaData()
#2 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1350): CActiveRecord->getTableSchema()
#3 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1456): CActiveRecord->query(Object(CDbCriteria))
#4 D:\xampp\htdocs\erp_started\protected\components\UserIdentity.php(21): CActiveRecord->find('LOWER(username)...', Array)
#5 D:\xampp\htdocs\erp_started\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#6 D:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#7 D:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#8 D:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#9 D:\xampp\htdocs\erp_started\protected\controllers\SiteController.php(94): CModel->validate()
#10 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#11 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#15 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#16 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/erp_started/index.php?r=site/login
HTTP_REFERER=http://localhost/erp_started/index.php?r=site/login
---
2014/12/19 05:02:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested detalle venta does not exist.' in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:527
Stack trace:
#0 D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php(501): DetalleVentaController->loadVenta(NULL)
#1 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterVentaContext(Object(CFilterChain))
#2 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#3 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#8 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('')
#10 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('DetalleVenta')
#11 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/erp_started/index.php?r=DetalleVenta
---
2014/12/19 05:07:44 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=DetalleVenta/create_venta2&pid=4885
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:09:13 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=DetalleVenta/create_venta2&pid=4884
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:09:25 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=DetalleVenta/create_venta2&pid=4886
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:22:12 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=DetalleVenta/create_venta2&pid=4886
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:22:19 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=DetalleVenta/create_venta2&pid=3
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:26:46 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=DetalleVenta/create_venta2&pid=4
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:41:14 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=detalleVenta/create_venta2&pid=4
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:43:43 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=detalleVenta/create_venta2&pid=4
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:44:06 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=detalleVenta/create_venta2&pid=4
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:44:14 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=detalleVenta/create_venta2&pid=4
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:44:15 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=detalleVenta/create_venta2&pid=4
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:44:36 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=detalleVenta/create_venta2&pid=4887
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:44:41 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=detalleVenta/create_venta2&pid=4887
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:44:46 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=detalleVenta/create_venta2&pid=4887
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:44:48 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=detalleVenta/create_venta2&pid=4887
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:46:43 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=detalleVenta/create_venta2&pid=4887
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:48:24 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=detalleVenta/create_venta2&pid=4887
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:48:39 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=detalleVenta/create_venta2&pid=4887
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:48:54 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=detalleVenta/create_venta2&pid=4887
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:49:29 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=detalleVenta/create_venta2&pid=4887
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 05:52:25 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:127)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=detalleVenta/create_venta2&pid=4887
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (127)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 22:40:50 [error] [system.db.CDbCommand] CDbCommand::fetchAll() falló: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'erp_started2.tbl_user' doesn't exist. La sentencia SQL ejecutada fue: SHOW FULL COLUMNS FROM `tbl_user`.
in D:\xampp\htdocs\erp_started\protected\components\UserIdentity.php (21)
in D:\xampp\htdocs\erp_started\protected\models\LoginForm.php (52)
in D:\xampp\htdocs\erp_started\protected\controllers\SiteController.php (94)
2014/12/19 22:40:50 [error] [exception.CDbException] exception 'CDbException' with message 'La tabla "tbl_user" definida en la clase active record "User" no se ha podido encontrar en la base de datos.' in D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php:2362
Stack trace:
#0 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(User))
#1 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(658): CActiveRecord->getMetaData()
#2 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1350): CActiveRecord->getTableSchema()
#3 D:\xampp\htdocs\yii\framework\db\ar\CActiveRecord.php(1456): CActiveRecord->query(Object(CDbCriteria))
#4 D:\xampp\htdocs\erp_started\protected\components\UserIdentity.php(21): CActiveRecord->find('LOWER(username)...', Array)
#5 D:\xampp\htdocs\erp_started\protected\models\LoginForm.php(52): UserIdentity->authenticate()
#6 D:\xampp\htdocs\yii\framework\validators\CInlineValidator.php(42): LoginForm->authenticate('password', Array)
#7 D:\xampp\htdocs\yii\framework\validators\CValidator.php(213): CInlineValidator->validateAttribute(Object(LoginForm), 'password')
#8 D:\xampp\htdocs\yii\framework\base\CModel.php(159): CValidator->validate(Object(LoginForm), NULL)
#9 D:\xampp\htdocs\erp_started\protected\controllers\SiteController.php(94): CModel->validate()
#10 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#11 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#12 D:\xampp\htdocs\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#13 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#14 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('login')
#15 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#16 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#18 {main}
REQUEST_URI=/Erp_started/index.php?r=site/login
HTTP_REFERER=http://localhost/Erp_started/index.php?r=site/login
---
2014/12/19 22:47:26 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:130)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/Erp_started/index.php?r=detalleVenta/create_venta2&pid=4888
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (130)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/19 22:47:37 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:130)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): DetalleVentaController->runAction()
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterAccessControl()
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): DetalleVentaController->runActionWithFilters()
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): DetalleVentaController->run()
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/Erp_started/index.php?r=detalleVenta/create_venta2&pid=4888
in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php (130)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/20 08:10:29 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in D:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('almacen/admin')
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/Erp_started/index.php?r=almacen/admin
HTTP_REFERER=http://localhost/Erp_started/index.php?r=almacen
---
2014/12/20 08:10:42 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in D:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('almacen/admin')
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/Erp_started/index.php?r=almacen/admin
HTTP_REFERER=http://localhost/Erp_started/index.php?r=almacen/create
---
2014/12/20 08:13:02 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in D:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('almacen/admin')
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/Erp_started/index.php?r=almacen/admin
HTTP_REFERER=http://localhost/Erp_started/index.php?r=almacen/create
---
2014/12/20 08:14:38 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'Usted no se encuentra autorizado a realizar esta acción.' in D:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'Usted no se enc...')
#1 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#6 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('create')
#8 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('almacen/create')
#9 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/Erp_started/index.php?r=almacen/create
HTTP_REFERER=http://localhost/Erp_started/index.php?r=almacen
---
2014/12/20 08:34:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'No es posible resolver la solicitud "ventas/admin"' in D:\xampp\htdocs\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('ventas/admin')
#1 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Erp_started/index.php?r=ventas/admin
---
2014/12/23 16:46:24 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'erp_plastiplas.tbl_migration' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_migration`.
2014/12/23 17:06:24 [error] [php] Trying to get property of non-object (D:\xampp\htdocs\yii\framework\base\CComponent.php(612) : eval()'d code:1)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\zii\widgets\grid\CGridColumn.php(151): TbDataColumn->renderDataCellContent()
#1 D:\xampp\htdocs\yii\framework\zii\widgets\grid\CGridView.php(616): TbDataColumn->renderDataCell()
#2 D:\xampp\htdocs\yii\framework\zii\widgets\grid\CGridView.php(572): TbGridView->renderTableRow()
#3 D:\xampp\htdocs\yii\framework\zii\widgets\grid\CGridView.php(482): TbGridView->renderTableBody()
#4 D:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(167): TbGridView->renderItems()
#5 unknown(0): TbGridView->renderSection()
#6 D:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(150): preg_replace_callback()
#7 D:\xampp\htdocs\yii\framework\zii\widgets\CBaseListView.php(135): TbGridView->renderContent()
#8 D:\xampp\htdocs\yii\framework\web\CBaseController.php(173): TbGridView->run()
#9 D:\xampp\htdocs\erp_started\protected\views\unidadMedida\admin.php(72): UnidadMedidaController->widget()
#10 D:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require()
#11 D:\xampp\htdocs\yii\framework\web\CBaseController.php(95): UnidadMedidaController->renderInternal()
#12 D:\xampp\htdocs\yii\framework\web\CController.php(869): UnidadMedidaController->renderFile()
#13 D:\xampp\htdocs\yii\framework\web\CController.php(782): UnidadMedidaController->renderPartial()
#14 D:\xampp\htdocs\erp_started\protected\controllers\UnidadMedidaController.php(148): UnidadMedidaController->render()
#15 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(49): UnidadMedidaController->actionAdmin()
#16 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#17 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): UnidadMedidaController->runAction()
#18 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#19 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#20 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): UnidadMedidaController->filterAccessControl()
#21 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#22 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#23 D:\xampp\htdocs\yii\framework\web\CController.php(265): UnidadMedidaController->runActionWithFilters()
#24 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): UnidadMedidaController->run()
#25 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#26 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#27 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=unidadMedida/admin
in D:\xampp\htdocs\erp_started\protected\views\unidadMedida\admin.php (72)
in D:\xampp\htdocs\erp_started\protected\controllers\UnidadMedidaController.php (148)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/23 18:46:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The requested detalle venta does not exist.' in D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php:558
Stack trace:
#0 D:\xampp\htdocs\erp_started\protected\controllers\DetalleVentaController.php(530): DetalleVentaController->loadVenta(NULL)
#1 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): DetalleVentaController->filterVentaContext(Object(CFilterChain))
#2 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#3 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#4 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#5 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#6 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#7 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#8 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('admin')
#10 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('DetalleVenta/ad...')
#11 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/erp_started/index.php?r=DetalleVenta/admin
---
2014/12/23 23:22:42 [error] [php] Undefined variable: _header (D:\xampp\htdocs\erp_started\protected\views\layouts\print.php:478)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(784): VentaController->renderFile()
#1 D:\xampp\htdocs\erp_started\protected\controllers\VentaController.php(56): VentaController->render()
#2 unknown(0): VentaController->actionView()
#3 D:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs()
#4 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): VentaController->runAction()
#7 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#8 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#9 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): VentaController->filterAccessControl()
#10 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#11 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#12 D:\xampp\htdocs\yii\framework\web\CController.php(265): VentaController->runActionWithFilters()
#13 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): VentaController->run()
#14 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#15 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#16 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=venta/view&id=1
in D:\xampp\htdocs\erp_started\protected\views\layouts\print.php (478)
in D:\xampp\htdocs\erp_started\protected\controllers\VentaController.php (56)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/23 23:23:33 [error] [php] Undefined variable: _header (D:\xampp\htdocs\erp_started\protected\views\layouts\print.php:478)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(784): VentaController->renderFile()
#1 D:\xampp\htdocs\erp_started\protected\controllers\VentaController.php(56): VentaController->render()
#2 unknown(0): VentaController->actionView()
#3 D:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs()
#4 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): VentaController->runAction()
#7 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#8 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#9 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): VentaController->filterAccessControl()
#10 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#11 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#12 D:\xampp\htdocs\yii\framework\web\CController.php(265): VentaController->runActionWithFilters()
#13 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): VentaController->run()
#14 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#15 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#16 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=venta/view&id=1
in D:\xampp\htdocs\erp_started\protected\views\layouts\print.php (478)
in D:\xampp\htdocs\erp_started\protected\controllers\VentaController.php (56)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/23 23:28:12 [error] [php] Undefined variable: _header (D:\xampp\htdocs\erp_started\protected\views\layouts\print.php:478)
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CController.php(784): VentaController->renderFile()
#1 D:\xampp\htdocs\erp_started\protected\controllers\VentaController.php(56): VentaController->render()
#2 unknown(0): VentaController->actionView()
#3 D:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs()
#4 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CInlineAction->runWithParamsInternal()
#5 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#6 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): VentaController->runAction()
#7 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#8 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CAccessControlFilter->filter()
#9 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): VentaController->filterAccessControl()
#10 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter()
#11 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#12 D:\xampp\htdocs\yii\framework\web\CController.php(265): VentaController->runActionWithFilters()
#13 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): VentaController->run()
#14 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#15 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#16 D:\xampp\htdocs\erp_started\index.php(13): CWebApplication->run()
REQUEST_URI=/erp_started/index.php?r=venta/view&id=1
in D:\xampp\htdocs\erp_started\protected\views\layouts\print.php (478)
in D:\xampp\htdocs\erp_started\protected\controllers\VentaController.php (56)
in D:\xampp\htdocs\erp_started\index.php (13)
2014/12/23 23:34:03 [error] [exception.CException] exception 'CException' with message 'VentaController tiene una llamada extra a endWidget(CContentDecorator) en su vista.' in D:\xampp\htdocs\yii\framework\web\CBaseController.php:210
Stack trace:
#0 D:\xampp\htdocs\yii\framework\web\CBaseController.php(300): CBaseController->endWidget('CContentDecorat...')
#1 D:\xampp\htdocs\erp_started\protected\views\layouts\print.php(472): CBaseController->endContent()
#2 D:\xampp\htdocs\yii\framework\web\CBaseController.php(126): require('D:\xampp\htdocs...')
#3 D:\xampp\htdocs\yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('D:\xampp\htdocs...', Array, true)
#4 D:\xampp\htdocs\yii\framework\web\CController.php(784): CBaseController->renderFile('D:\xampp\htdocs...', Array, true)
#5 D:\xampp\htdocs\erp_started\protected\controllers\VentaController.php(56): CController->render('view', Array)
#6 [internal function]: VentaController->actionView('1')
#7 D:\xampp\htdocs\yii\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(VentaController), Array)
#8 D:\xampp\htdocs\yii\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(VentaController), Object(ReflectionMethod), Array)
#9 D:\xampp\htdocs\yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#10 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(133): CController->runAction(Object(CInlineAction))
#11 D:\xampp\htdocs\yii\framework\web\filters\CFilter.php(40): CFilterChain->run()
#12 D:\xampp\htdocs\yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#13 D:\xampp\htdocs\yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#14 D:\xampp\htdocs\yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#15 D:\xampp\htdocs\yii\framework\web\CController.php(291): CFilterChain->run()
#16 D:\xampp\htdocs\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#17 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(282): CController->run('view')
#18 D:\xampp\htdocs\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('venta/view')
#19 D:\xampp\htdocs\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#20 D:\xampp\htdocs\erp_started\index.php(13): CApplication->run()
#21 {main}
REQUEST_URI=/erp_started/index.php?r=venta/view&id=1
---
